eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8700/eureka/,http://localhost:8701/eureka/
      defaultZone: http://localhost:8700/eureka/
server:
  port: 8741
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign