server:
  port: 8712

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
#      defaultZone: http://localhost:8700/eureka/,http://localhost:8701/eureka/