server:
  port: 8988
spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: service-hi
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/