eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8700/eureka/,http://localhost:8701/eureka/
      defaultZone: http://localhost:8700/eureka/
server:
  port: 8731
spring:
  application:
    name: service-feign